---
mmdebstrap:
  suite: bookworm
  components:
    - main
    - contrib
    - non-free
    - non-free-firmware
  architectures:
    - arm64
  variant: minbase
  packages:
    - ca-certificates
    - sudo
    - tzdata
    - locales
    - debian-archive-keyring
    # required for working DNS inside chroot:
    - libnss-dns
    - netbase
