#!/usr/bin/env bash
set -euxo pipefail
export LC_ALL=C

source /common.sh
install_cleanup_trap
[ -r /files/ks_helpers.sh ] && source /files/ks_helpers.sh

export DEBIAN_FRONTEND=noninteractive

section "Camera stack (RPi/OPi) — backends + policy"

# Detect board
MODEL_FILE="/proc/device-tree/model"
COMPAT_FILE="/proc/device-tree/compatible"
is_rpi=false; is_orangepi=false
if grep -q "Raspberry Pi" "$MODEL_FILE" 2>/dev/null || grep -qi "raspberrypi" "$COMPAT_FILE" 2>/dev/null; then
  is_rpi=true
elif grep -qiE "orangepi|orange pi" "$MODEL_FILE" 2>/dev/null || grep -qi "orangepi" "$COMPAT_FILE" 2>/dev/null; then
  is_orangepi=true
fi

# Common tools
apt_update_once || true
apt_install v4l-utils ffmpeg ustreamer || true

# RPi libcamera/libraspberrypi stack
if $is_rpi; then
  section "RPi: install libcamera + firmware userspace"
  apt_install libraspberrypi0 libraspberrypi-bin libcamera0 libcamera-dev || true
fi

# Non-RPi (e.g., Orange Pi 5 Max): camera-streamer preferred
have_cs=0
if ! $is_rpi; then
  section "Non-RPi: install camera-streamer (preferred)"
  if DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install camera-streamer; then
    have_cs=1
  else
    section "Attempt prebuilt camera-streamer package"
    : "${CAMERA_STREAMER_VERSION:=0.2.8}"
    . /etc/os-release || true
    CODENAME="${VERSION_CODENAME:-bookworm}"
    ARCH="$(dpkg --print-architecture)"
    BASE="https://github.com/ayufan/camera-streamer/releases/download/v${CAMERA_STREAMER_VERSION}"
    # First try generic build
    PKG="camera-streamer-generic_${CAMERA_STREAMER_VERSION}.${CODENAME}_${ARCH}.deb"
    TMP="/tmp/${PKG}"
    if curl -fsSL -o "$TMP" "${BASE}/${PKG}"; then
      apt-get -y install "$TMP" && have_cs=1 || true
    else
      # Last resort: SoC-specific (best-effort)
      for FLAV in rk3588 rk3399 generic; do
        PKG="camera-streamer-${FLAV}_${CAMERA_STREAMER_VERSION}.${CODENAME}_${ARCH}.deb"
        TMP="/tmp/${PKG}"
        if curl -fsSL -o "$TMP" "${BASE}/${PKG}"; then
          apt-get -y install "$TMP" && have_cs=1 && break || true
        fi
      done
    fi
  fi
fi

# Policy file consumed later by 99-enable-units.sh
install -d -m 0755 /etc/crowsnest
PREF="ustreamer"
if [ "$have_cs" -eq 1 ]; then
  PREF="camera-streamer"
elif $is_rpi; then
  PREF="ustreamer"
else
  PREF="ustreamer"
fi

cat >/etc/crowsnest/policy.conf <<EOF
# Generated by 14-camera-stack.sh
[policy]
mode=auto
prefer=${PREF}
EOF

echo "[camera] policy prefer=${PREF} (is_rpi=${is_rpi}, is_orangepi=${is_orangepi})"

apt_clean_all || true
