#!/usr/bin/env bash
set -euxo pipefail
export LC_ALL=C

source /common.sh
install_cleanup_trap
[ -r /files/ks_helpers.sh ] && source /files/ks_helpers.sh

export DEBIAN_FRONTEND=noninteractive

section "Camera stack (RPi/OPi) — backends + policy"

# Detect board
MODEL_FILE="/proc/device-tree/model"
COMPAT_FILE="/proc/device-tree/compatible"
is_rpi=false; is_orangepi=false
if grep -q "Raspberry Pi" "$MODEL_FILE" 2>/dev/null || grep -qi "raspberrypi" "$COMPAT_FILE" 2>/dev/null; then
  is_rpi=true
elif grep -qiE "orangepi|orange pi" "$MODEL_FILE" 2>/dev/null || grep -qi "orangepi" "$COMPAT_FILE" 2>/dev/null; then
  is_orangepi=true
fi

# Policy file consumed later by 99-enable-units.sh
install -d -m 0755 /etc/crowsnest
PREF="ustreamer"
if [ "$have_cs" -eq 1 ]; then
  PREF="camera-streamer"
elif $is_rpi; then
  PREF="ustreamer"
else
  PREF="ustreamer"
fi

cat >/etc/crowsnest/policy.conf <<EOF
# Generated by 14-camera-stack.sh
[policy]
mode=auto
prefer=${PREF}
EOF

echo "[camera] policy prefer=${PREF} (is_rpi=${is_rpi}, is_orangepi=${is_orangepi})"
