name: Build & Customize (Klipper Suite)

on:
  push:
    branches: [ master ]
    paths:
      - 'bconf/**'
      - 'devices/**'
      - 'scripts/**'
      - 'custopizer/**'
      - '.github/workflows/build-and-customize.yml'
  workflow_dispatch:
    inputs:
      device:
        description: "Device key (rpi64 or orangepi5max)"
        required: true
        default: "rpi64"
      board:
        description: "OPi board hint (orangepi5 | orangepi5-plus | orangepi5-max)"
        required: false
      ks_user:
        description: "Username in image (fallback: pi)"
        required: false
      kernel_console:
        description: "Kernel console (OPi only)"
        required: false
      extra_append:
        description: "Extra kernel args (Pi + OPi)"
        required: false
      arg_strategy:
        description: "append | replace (kernel args merge)"
        required: false
        default: "append"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-customize:
    runs-on: ubuntu-latest
    env:
      DEVICE: ${{ github.event.inputs.device }}
      KS_USER: ${{ github.event.inputs.ks_user }}
      BOARD: ${{ github.event.inputs.board }}
      KERNEL_CONSOLE: ${{ github.event.inputs.kernel_console }}
      EXTRA_APPEND: ${{ github.event.inputs.extra_append }}
      ARG_STRATEGY: ${{ github.event.inputs.arg_strategy }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install host deps
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y bdebstrap mmdebstrap debian-archive-keyring qemu-user-static binfmt-support podman wget gpg curl rsync unzip parted dosfstools util-linux e2fsprogs
          sudo update-binfmts --enable qemu-aarch64 || true

      - name: Set defaults for non-dispatch runs
        run: |
          echo "DEVICE=${DEVICE:-rpi64}" >> "$GITHUB_ENV"
          echo "BOARD=${BOARD:-}" >> "$GITHUB_ENV"
          echo "KS_USER=${KS_USER:-}" >> "$GITHUB_ENV"
          echo "KERNEL_CONSOLE=${KERNEL_CONSOLE:-}" >> "$GITHUB_ENV"
          echo "EXTRA_APPEND=${EXTRA_APPEND:-}" >> "$GITHUB_ENV"
          echo "ARG_STRATEGY=${ARG_STRATEGY:-append}" >> "$GITHUB_ENV"

      - name: Build base rootfs (${DEVICE})
        run: |
          set -euxo pipefail
          bash scripts/build-device.sh

      - name: Assemble base image (RPi64)
        if: env.DEVICE == 'rpi64'
        env:
          EXTRA_APPEND: ${{ github.event.inputs.extra_append }}
          ARG_STRATEGY: ${{ github.event.inputs.arg_strategy }}
        run: |
          set -euxo pipefail
          echo "ARG_STRATEGY: ${ARG_STRATEGY:-append}"
          echo "EXTRA_APPEND: ${EXTRA_APPEND:-<none>}"
          bash scripts/make-img-rpi.sh "out/${DEVICE}-bookworm-arm64/rootfs" "build/input-${DEVICE}.img"

      - name: Assemble base image (Orange Pi 5 family)
        if: env.DEVICE == 'orangepi5max'
        env:
          BOARD: ${{ github.event.inputs.board }}
          KERNEL_CONSOLE: ${{ github.event.inputs.kernel_console }}
          EXTRA_APPEND: ${{ github.event.inputs.extra_append }}
          ARG_STRATEGY: ${{ github.event.inputs.arg_strategy }}
        run: |
          set -euxo pipefail
          echo "BOARD: ${BOARD:-<auto-detect>}"
          echo "ARG_STRATEGY: ${ARG_STRATEGY:-append}"
          echo "KERNEL_CONSOLE: ${KERNEL_CONSOLE:-<default>}"
          echo "EXTRA_APPEND: ${EXTRA_APPEND:-<none>}"
          bash scripts/make-img-orangepi5max.sh "out/${DEVICE}-bookworm-arm64/rootfs" "build/input-${DEVICE}.img"

      - name: Prepare CustoPiZer workspace
        run: |
          set -eux
          mkdir -p build/workspace
          cp -f "build/input-${DEVICE}.img" build/workspace/input.img
          chmod -R +x custopizer/custom.d
          cat > build/config.local <<'EOF'
          EDITBASE_ARCH=arm64
          EDITBASE_IMAGE_ENLARGEROOT=8000
          # Optional: final resize to +20% after customization
          EDITBASE_IMAGE_RESIZEROOT=20
          EOF

      - name: Run CustoPiZer
        uses: OctoPrint/CustoPiZer@main
        with:
          workspace: "${{ github.workspace }}/build/workspace"
          scripts:   "${{ github.workspace }}/custopizer/custom.d"
          config:    "${{ github.workspace }}/build/config.local"

      - name: Collect customized image
        run: |
          set -euxo pipefail
          test -s build/workspace/output.img
          mv -f build/workspace/output.img "build/output-${DEVICE}.img"

      - name: Upload customized image
        uses: actions/upload-artifact@v4
        with:
          name: klipper-suite-${{ env.DEVICE }}
          path: build/output-${{ env.DEVICE }}.img
