name: Build and Customize (Klipper Suite)

on:
  push:
    branches: [ master, develop, "**" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device: [ rpi64 ]   # add more later, e.g. orangepi5max
    env:
      DEVICE: ${{ matrix.device }}
      ENLARGEROOT: "8000"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install mmdebstrap (v1.5.7) + bdebstrap (from GitHub)+ host deps (qemu-user, tooling)
        env:
          MMDEBSTRAP_REF: "1.5.7"      # tag name on GitLab (no 'v' prefix)
          BDEBSTRAP_REF:  v0.7.0       # pick your preferred tag or 'main'
        shell: bash
        run: |
          set -euo pipefail

          # Robust defaults even if env is missing or empty
          MM_TAG="${MMDEBSTRAP_TAG:-1.5.7}"
          BDEB_REF="${BDEBSTRAP_REF:-v0.7.0}"

          # OS-level tools you need regardless
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            qemu-user-static binfmt-support pandoc arch-test \
            ca-certificates curl wget jq git unzip rsync \
            parted dosfstools e2fsprogs kpartx xz-utils \
            util-linux udev mount kmod file perl python3-pip \
            debian-archive-keyring 

          # Make sure binfmt registrations are active
          sudo update-binfmts --enable qemu-aarch64 || true
          sudo update-binfmts --enable qemu-arm || true

          # Sanity checks (should print "arm64: yes")
          arch-test arm64
          qemu-aarch64-static --version

          # ---- mmdebstrap from GitLab (clone the exact tag) ----
          rm -rf mmdebstrap-src
          git clone --depth=1 --branch "${MM_TAG}" \
            https://gitlab.mister-muffin.de/josch/mmdebstrap.git mmdebstrap-src || {
            echo "Direct clone of tag ${MM_TAG} failed, trying with 'v' prefix…"
            git clone --depth=1 --branch "v${MM_TAG}" \
              https://gitlab.mister-muffin.de/josch/mmdebstrap.git mmdebstrap-src
          }

          sudo install -D -m 0755 mmdebstrap-src/mmdebstrap /usr/local/bin/mmdebstrap
          # Optional extras if present in this tag:
          [ -f mmdebstrap-src/mmdebstrap.1 ] && \
            sudo install -D -m 0644 mmdebstrap-src/mmdebstrap.1 /usr/local/share/man/man1/mmdebstrap.1 || true
          [ -d mmdebstrap-src/share/mmdebstrap ] && \
            sudo mkdir -p /usr/local/share/mmdebstrap && \
            sudo cp -a mmdebstrap-src/share/mmdebstrap/. /usr/local/share/mmdebstrap/ || true

          # -------- bdebstrap from upstream GitHub --------
          python3 -m pip install --user --upgrade pip wheel
          python3 -m pip install --user "git+https://github.com/bdrung/bdebstrap@${BDEB_REF}"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Build rootfs with bdebstrap
        run: |
          bash scripts/build-bdebstrap.sh "${DEVICE}" "devices/${DEVICE}/layers.yaml" "out/${DEVICE}-bookworm-arm64"

      - name: Make bootable image (Raspberry Pi)
        if: matrix.device == 'rpi64'
        run: |
          sudo bash scripts/make-img-rpi.sh "out/${DEVICE}-bookworm-arm64/rootfs" "build/input-${DEVICE}.img"

      # Example placeholder for other devices:
      # - name: Make bootable image (Orange Pi 5 Max)
      #   if: matrix.device == 'orangepi5max'
      #   run: |
      #     echo "TODO: add orange pi image builder (u-boot/extlinux)"; exit 1

      # --- BEGIN: inline CustoPiZer run (replaces scripts/run-CustoPiZer.sh) ---
      - name: Create CustoPiZer config.local
        shell: bash
        run: |
          set -eux

          # Decide distro for CustoPiZer based on DEVICE:
          #   - raspbian for Raspberry Pi targets (e.g. rpi64)
          #   - armbian for everything else (e.g. orangepi5max)
          case "${DEVICE:-rpi64}" in
            rpi*|raspberrypi* ) DISTRO="raspbian" ;;
            * )                 DISTRO="armbian"  ;;
          esac

          cat > "${GITHUB_WORKSPACE}/config.local" <<'EOF'
          # Auto-generated by GitHub Actions
          # See https://github.com/OctoPrint/CustoPiZer for details

          # Distro selector (raspbian|armbian)
          EDITBASE_DISTRO=@DISTRO@

          # Mount proc/sys into chroot (required for many scripts)
          EDITBASE_MOUNT_PROC=1
          EDITBASE_MOUNT_SYS=1

          # Grow rootfs by +8000 MiB, then shrink to minimum + 100 MiB slack
          EDITBASE_IMAGE_ENLARGEROOT=8000
          EDITBASE_IMAGE_RESIZEROOT=100

          # Force chroot arch when needed
          EDITBASE_ARCH=arm64
          EOF

          # Inject computed DISTRO into the template
          sed -i "s/@DISTRO@/${DISTRO}/g" "${GITHUB_WORKSPACE}/config.local"

      # Ensure build dir is writable by the runner
      - name: Fix build directory ownership (pre-normalize)
        shell: bash
        run: |
          set -eux
          sudo mkdir -p build
          sudo chown -R "$USER":"$USER" build
          chmod -R u+rwX build

      - name: Normalize input image name to build/input.img
        shell: bash
        run: |
          set -eux
          # If target exists from a previous run, remove it even if it's root-owned
          sudo rm -f build/input.img
          # Chown the source file in case it's root-owned
          sudo chown "$USER":"$USER" "build/input-${DEVICE}.img"
          mv -f "build/input-${DEVICE}.img" "build/input.img"

      - name: Run CustoPiZer (raw docker)
        shell: bash
        run: |
          set -eux
          # Work around occasional DNS hiccups in CI by injecting a resolver
          docker run --rm --privileged \
            --dns 8.8.8.8 \
            -v "${GITHUB_WORKSPACE}/build:/CustoPiZer/workspace" \
            -v "${GITHUB_WORKSPACE}/config.local:/CustoPiZer/config.local" \
            ghcr.io/octoprint/custopizer:latest

          # CustoPiZer writes build/output.img; rename with device suffix
          mv -f "${GITHUB_WORKSPACE}/build/output.img" \
          "${GITHUB_WORKSPACE}/build/output-${DEVICE}.img"

      # Take back ownership of the output from CustoPiZer (it runs as root)
      - name: Fix build directory ownership (post-CustoPiZer)
        shell: bash
        run: |
          set -eux
          sudo chown -R "$USER":"$USER" build
          chmod -R u+rwX build

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ env.DEVICE }}.img
          path: build/output-${{ env.DEVICE }}.img
