name: Customize with CustoPiZer

on:
  # Auto-trigger when the base workflow completes successfully
  workflow_run:
    workflows: [ "Build Base Image" ]
    types: [ completed ]
  # Manual trigger for focused debugging
  workflow_dispatch:
    inputs:
      device:
        description: "Target device (e.g. rpi64, orangepi5max)"
        required: true
        default: "rpi64"
      base_run_id:
        description: "Optional: specific run ID of 'Build Base Image' to pull from"
        required: false

permissions:
  actions: read
  contents: read

concurrency:
  group: customize-${{ github.ref }}
  cancel-in-progress: true

jobs:
  customize:
    runs-on: ubuntu-latest
    env:
      DEVICE: ${{ github.event_name == 'workflow_dispatch' && inputs.device || 'rpi64' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Ensure scripts dir & perms
        shell: bash
        run: |
          set -eux
          test -d scripts
          chmod -R a+rx scripts

      # ---- Download the base artifact from the other workflow run ----
      # Case 1: triggered by workflow_run (preferred path for chaining)
      - name: Download artifact from triggering base run
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: base-input-${{ env.DEVICE }}
          path: build

      # Case 2: manual dispatch with specific run id
      - name: Download artifact from specific run (manual)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.base_run_id != '' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ inputs.base_run_id }}
          name: base-input-${{ env.DEVICE }}
          path: build

      # Case 3: manual dispatch without run id -> fetch the latest successful artifact
      - name: Download latest successful artifact (manual fallback)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.base_run_id == '' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-base-image.yml
          workflow_conclusion: success
          name: base-input-${{ env.DEVICE }}
          path: build
          branch: ${{ github.ref_name }}

      - name: Verify artifact
        shell: bash
        run: |
          set -eux
          ls -l build
          # dawidd6/action-download-artifact extracts to a folder; normalize
          if [[ -d "build/base-input-${DEVICE}" ]]; then
            mv "build/base-input-${DEVICE}/input-${DEVICE}.img" "build/input-${DEVICE}.img" || true
          fi
          # Also try typical extraction path when artifact is a single file
          if [[ -f "build/input-${DEVICE}.img" ]]; then
            :
          elif [[ -f "build/input-${DEVICE}.img/input-${DEVICE}.img" ]]; then
            mv "build/input-${DEVICE}.img/input-${DEVICE}.img" "build/input-${DEVICE}.img"
          elif [[ -f "build/base-input-${DEVICE}.img" ]]; then
            mv "build/base-input-${DEVICE}.img" "build/input-${DEVICE}.img"
          fi
          test -s "build/input-${DEVICE}.img"

      - name: Create CustoPiZer config.local
        shell: bash
        run: |
          set -eux
          case "${DEVICE:-rpi64}" in
            rpi*|raspberrypi* ) DISTRO="raspbian" ;;
            * )                 DISTRO="armbian"  ;;
          esac

          cat > "${GITHUB_WORKSPACE}/config.local" <<'EOF'
          # Generated by workflow
          EDITBASE_DISTRO=@DISTRO@
          EDITBASE_MOUNT_PROC=1
          EDITBASE_MOUNT_SYS=1
          EDITBASE_IMAGE_ENLARGEROOT=8000
          EDITBASE_IMAGE_RESIZEROOT=100
          EDITBASE_ARCH=arm64
          EOF

          sed -i "s/@DISTRO@/${DISTRO}/g" "${GITHUB_WORKSPACE}/config.local"

      - name: Prepare workspace & rename to input.img
        shell: bash
        run: |
          set -eux
          sudo mkdir -p build
          sudo chown -R "$USER":"$USER" build
          chmod -R u+rwX build
          mv -f "build/input-${DEVICE}.img" "build/input.img"
          ls -lh build

      - name: Pull CustoPiZer image
        run: |
          set -eux
          docker pull ghcr.io/octoprint/custopizer:latest

      - name: Sanitize CustoPiZer scripts (no sudo in chroot)
        shell: bash
        run: |
          set -eux
          test -d scripts
          # Replace common sudo patterns with chroot-safe equivalents
          for f in scripts/*.sh; do
            # Skip non-regular files
            [ -f "$f" ] || continue
            sed -i \
              -e 's/sudo[[:space:]]\+-u[[:space:]]\+pi[[:space:]]\+/runuser -u pi -- /g' \
              -e 's/\bsudo[[:space:]]\+apt-get\b/apt-get/g' \
              -e 's/\bsudo[[:space:]]\+apt\b/apt/g' \
              -e 's/\bsudo[[:space:]]\+systemctl\b/systemctl/g' \
              -e 's/\bsudo[[:space:]]\+chown\b/chown/g' \
              "$f"
            # Drop any lingering attempts to install policykit-1 in chroot
            sed -i -e '/apt-get[[:space:]]\+-y[[:space:]]\+install[[:space:]]\+policykit-1/d' "$f" || true
          done
          chmod -R a+rx scripts

      - name: Run CustoPiZer (raw docker, explicit DNS)
        shell: bash
        run: |
          set -eux
          docker run --rm --privileged \
            --dns 8.8.8.8 --dns 1.1.1.1 \
            -v "${GITHUB_WORKSPACE}/build:/CustoPiZer/workspace" \
            -v "${GITHUB_WORKSPACE}/scripts:/CustoPiZer/workspace/scripts" \
            -v "${GITHUB_WORKSPACE}/config.local:/CustoPiZer/config.local" \
            ghcr.io/octoprint/custopizer:latest

          mv -f "${GITHUB_WORKSPACE}/build/output.img" \
                "${GITHUB_WORKSPACE}/build/output-${DEVICE}.img"

      - name: Upload customized image
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ env.DEVICE }}.img
          path: build/output-${{ env.DEVICE }}.img
