name: Customize with CustoPiZer

on:
  # Auto-trigger when the base workflow completes successfully
  workflow_run:
    workflows: [ "Build Base Image" ]
    types: [ completed ]
  # Manual trigger for focused debugging
  workflow_dispatch:
    inputs:
      device:
        description: "Target device (e.g. rpi64, orangepi5max)"
        required: true
        default: "rpi64"
      base_run_id:
        description: "Optional: specific run ID of 'Build Base Image' to pull from"
        required: false

permissions:
  actions: read
  contents: read

concurrency:
  group: customize-${{ github.ref }}
  cancel-in-progress: true

jobs:
  customize:
    runs-on: ubuntu-latest
    env:
      DEVICE: ${{ github.event_name == 'workflow_dispatch' && inputs.device || 'rpi64' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Ensure scripts dir & perms
        shell: bash
        run: |
          set -eux
          test -d scripts
          chmod -R a+rx scripts

      - name: Download artifact from that run (regex match, no unzip)
        uses: dawidd6/action-download-artifact@v11
        with:
          run_id: 16973650101
          name: ^base-input-rpi64(\.img(\.xz)?|\.zip)?$  # adjust DEVICE if needed
          name_is_regexp: true
          search_artifacts: true
          path: build
          skip_unpack: true
    
      - name: Extract artifact safely (handles >2GiB)
        shell: bash
        run: |
          set -eux
          ls -l build || true
          ZIP="$(find build -maxdepth 1 -type f -name '*.zip' | head -n1 || true)"
          if [[ -z "${ZIP}" ]]; then
            echo "No ZIP artifact found in build/"; exit 1
          fi

          sudo apt-get update
          # Try unzip; if not present or fails on big files, fall back to 7z
          if sudo apt-get install -y unzip; then
            unzip -o "${ZIP}" -d build || { sudo apt-get install -y p7zip-full; 7z x -y -o"build" "${ZIP}"; }
          else
            sudo apt-get install -y p7zip-full
            7z x -y -o"build" "${ZIP}"
          fi
          ls -l build

      - name: Normalize image path (supports .img and .img.xz)
        shell: bash
        run: |
          set -eux
          # Prefer exact device-named files, then any matching input-*.img(.xz)
          SRC="$(find build -maxdepth 4 -type f -name "input-${DEVICE}.img" -o -name "input-${DEVICE}.img.xz" | head -n1 || true)"
          if [[ -z "${SRC}" ]]; then
            SRC="$(find build -maxdepth 4 -type f \( -name "input-*.img" -o -name "input-*.img.xz" \) | head -n1 || true)"
          fi
          test -n "${SRC}" || (echo "No input image found after extraction"; exit 1)

          # If it's compressed (.xz), decompress to a file we control
          if [[ "${SRC}" == *.xz ]]; then
            sudo apt-get update && sudo apt-get install -y xz-utils
            xz -T0 -dk "${SRC}"            # leaves the .img next to it
            SRC="${SRC%.xz}"
          fi

      - name: Prepare workspace & rename to input.img
        shell: bash
        run: |
          set -eux
          sudo mkdir -p build
          sudo chown -R "$USER":"$USER" build
          chmod -R u+rwX build
          mv -f "build/input-${DEVICE}.img" "build/input.img"
          ls -lh build

      - name: Pull CustoPiZer image
        run: |
          set -eux
          docker pull ghcr.io/octoprint/custopizer:latest

      - name: Sanitize CustoPiZer scripts (no sudo in chroot)
        shell: bash
        run: |
          set -eux
          test -d scripts
          for f in scripts/*.sh; do
            [ -f "$f" ] || continue
            sed -i \
              -e 's/sudo[[:space:]]\+-u[[:space:]]\+pi[[:space:]]\+/runuser -u pi -- /g' \
              -e 's/\bsudo[[:space:]]\+apt-get\b/apt-get/g' \
              -e 's/\bsudo[[:space:]]\+apt\b/apt/g' \
              -e 's/\bsudo[[:space:]]\+systemctl\b/systemctl/g' \
              -e 's/\bsudo[[:space:]]\+chown\b/chown/g' \
              "$f"
            sed -i -e '/apt-get[[:space:]]\+-y[[:space:]]\+install[[:space:]]\+policykit-1/d' "$f" || true
          done
          chmod -R a+rx scripts

      - name: Select config.local for device
        shell: bash
        run: |
          set -euxo pipefail
          case "${DEVICE:-rpi64}" in
            rpi*|raspberrypi*) src=".github/custopizer/config.rpi64" ;;
            orangepi*|opi*)    src=".github/custopizer/config.orangepi" ;;
            *)                 src=".github/custopizer/config.rpi64" ;;  # default
          esac
          cp "$src" config.local
          echo "Using $(basename "$src"):"
          sed 's/^/  /' config.local

      - name: Pre-fix sudo perms inside input.img (non-interactive)
        shell: bash
        run: |
          set -euxo pipefail
          # Fix sudo/su ownership & setuid *inside* the image before CustoPiZer runs
          docker run --rm --privileged \
            -v "${GITHUB_WORKSPACE}/build/input.img:/image.img" \
            --entrypoint /bin/sh \
            ghcr.io/octoprint/custopizer:latest \
            -ec '
              set -eu
              apt-get update
              apt-get install -y kpartx e2fsprogs util-linux

              LOOP=$(losetup -Pf --show /image.img)
              partprobe "$LOOP" || true
              kpartx -av "$LOOP"

              MAP=$(basename "$LOOP")
              ROOTP=""
              if [ -e "/dev/mapper/${MAP}p2" ]; then
                ROOTP="/dev/mapper/${MAP}p2"
              else
                for p in /dev/mapper/${MAP}p*; do
                  [ -e "$p" ] || continue
                  if lsblk -no FSTYPE "$p" 2>/dev/null | grep -q "^ext4$"; then ROOTP="$p"; break; fi
                done
              fi
              [ -n "$ROOTP" ]

              mkdir -p /mnt/rootfs
              mount "$ROOTP" /mnt/rootfs

              chown 0:0 /mnt/rootfs/usr/bin/sudo  || true
              chmod 4755 /mnt/rootfs/usr/bin/sudo || true
              chown 0:0 /mnt/rootfs/etc/sudo.conf /mnt/rootfs/etc/sudoers || true
              chmod 0440 /mnt/rootfs/etc/sudoers  || true
              for su in /mnt/rootfs/bin/su /mnt/rootfs/usr/bin/su; do
                [ -e "$su" ] && { chown 0:0 "$su" || true; chmod 4755 "$su" || true; }
              done

              umount /mnt/rootfs
              kpartx -dv "$LOOP"
              losetup -d "$LOOP"
            '

      - name: Run CustoPiZer (raw docker, explicit DNS)
        shell: bash
        run: |
          set -eux
          docker run --rm --privileged \
            --dns 8.8.8.8 --dns 1.1.1.1 \
            -v "${GITHUB_WORKSPACE}/build:/CustoPiZer/workspace" \
            -v "${GITHUB_WORKSPACE}/scripts:/CustoPiZer/workspace/scripts" \
            -v "${GITHUB_WORKSPACE}/config.local:/CustoPiZer/config.local" \
            ghcr.io/octoprint/custopizer:latest

          mv -f "${GITHUB_WORKSPACE}/build/output.img" \
                "${GITHUB_WORKSPACE}/build/output-${DEVICE}.img"

      - name: Upload customized image
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ env.DEVICE }}.img
          path: build/output-${{ env.DEVICE }}.img
